# Generated by Django 3.2.6 on 2021-10-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='contents',
        ),
    ]
