from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("post/1", views.post1, name="post1"),
    path("post/2", views.post2, name="post2"),
    path("post/3", views.post3, name="post3"),
    path("post/4", views.post4, name="post4"),
    path("post/5", views.post5, name="post5"),
    path("post/6", views.post6, name="post6"),
    path("post/7", views.post7, name="post7"),
    path("post/8", views.post8, name="post8"),
    path("post/9", views.post9, name="post9"),
    path("post/10", views.post10, name="post10"),
    path("post/11", views.post11, name="post11"),
    path("post/12", views.post12, name="post12"),
    path("post/13", views.post13, name="post13"),
    path("post/14", views.post14, name="post14"),
    path("post/15", views.post15, name="post15"),
    path("post/16", views.post16, name="post16"),
    path("post/17", views.post17, name="post17"),
    path("post/18", views.post18, name="post18"),
    path("post/19", views.post19, name="post19"),
    path("post/20", views.post20, name="post20"),
    path("post/21", views.post21, name="post21"),
    path("post/22", views.post22, name="post22"),
    path("post/23", views.post23, name="post23"),
    path("post/24", views.post24, name="post24"),
    path("post/25", views.post25, name="post25"),
    path("post/26", views.post26, name="post26"),
    path("post/27", views.post27, name="post27"),
    path("post/28", views.post28, name="post28"),
    path("post/29", views.post29, name="post29"),
    path("post/30", views.post30, name="post30"),
    path("post/31", views.post31, name="post31"),
    path("post/32", views.post32, name="post32"),
    path("post/<int:blog_pk>", views.detail, name="detail"),
    path("post/category/basic", views.category_basic, name="category1"),
    path("post/category/c", views.category_c, name="category2"),
    path("post/category/algorithm", views.category_algorithm, name="category3"),
    path("post/category/math", views.category_math, name="category4"),
    path("post/category/os", views.category_os, name="category5"),
    path("", views.all_posts, name="all-posts"),
]
